<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CscToolPath)' == '' AND Exists('C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\Roslyn')">
    <CscToolPath>C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\Roslyn</CscToolPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ReportExample\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="test_data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
